#+title: Virtual mail server on Arch Linux
* Packages
#+BEGIN_EXAMPLE
amavisd-new certbot certbot-nginx clamav dovecot mailutils nginx opendkim php-imap php-pgsql postfix postfixadmin postgresql pyzor python-postfix-policyd-spf spamassassin
#+END_EXAMPLE
* Guide
** Start
*** This guide assumes a working Arch Linux web server running NGINX, PostgreSQL, and PHP.  In most cases, a well-configured server will already have a configured firewall and generated SSL certificates.  Some ports may need to be opened in the firewall to allow IMAP (143, 993) and SMTP (25, 465, 587) connections.  Existing certificates may be used instead of generating a new one.
** Configure DNS
*** Many VPS providers include DNS management tools.  For 
A entries: domain.com, hostname.domain.com, mail.domain.com
MX entries: mail.domain.com
Another entry will be added here later.  If you'd like, you can skip to the
OpenDKIM section now and follow the steps for key generation and DNS
modification.
TXT entries: mail._ dkim
** Issue SSL certificates 
If your site is already configured with a certificate and you'd like to use the
same one to sign your emails, skip this section and replace subsequent instances
of /etc/letsencrypt/live/example.com/priv.key with its path.
** Create the database
** Postfix and PostfixAdmin
*** If you don't need continued access to PostfixAdmin, it can be used to set up the tables and then be uninstalled.
Make the postfixAdmin site files accessible by adding an entry to
/etc/nginx/nginx.conf or by creating a symbolic link inside your web directory.
#+BEGIN_EXAMPLE
ln -s /usr/share/webapps/postfixAdmin/public /srv/http/example.com/html
#+END_EXAMPLE
Replace /srv/http/example.com/html with the base public directory for your site.
Navigate to example.com/postfixadmin/setup.php.
Paste the key into /etc/webapps/postfixadmin/config.local.php.
*** To create mailboxes manually, login to the database
Generate a hashed password:
#+BEGIN_EXAMPLE
doveadm pw -p PASSWORD -r 15 -s BLF-CRYPT
#+END_EXAMPLE
Where PASSWORD is the plaintext password you want to hash and 15 can be any
number between 4 and 31--the '-r' flag specifies how many rounds of encryption
to use.  Copy the output (including '{BLF-CRYPT}'.
Edit /etc/services and include 'submission   587/tcp' and 'submission 587/udp'
** Dovecot
** OpenDKIM
*** Permissions
The postfix user needs to be added to the opendkim group to avoid
permissions errors.
#+BEGIN_EXAMPLE
sudo usermod -aG opendkim postfix
#+END_EXAMPLE
Note: in Arch Linux, the =/var/run= folder is symlinked to =/run=.
Since permissions on symbolic links are overriden by those on the original
files, permissions need to be set on =/run/opendkim= rather than
=/var/run/opendkim=.  Make sure the owner and group of this directory is
set to =opendkim= by running:
#+BEGIN_EXAMPLE
sudo chown -R opendkim:opendkim /var/run/opendkim
#+END_EXAMPLE
Postfix should now have full acces to the milter and permissions
errors should be resolved.  Start and enable the OpenDKIM service and
reload Postfix.
#+BEGIN_EXAMPLE
sudo systemctl start opendkim
sudo systemctl enable opendkim
sudo systemctl restart postfix
#+END_EXAMPLE
** Spam and virus filtering
Packages =clamav= and =amavisd-new= both create their own system user and
group to manage their respective services.  Since the processes need
access to one another, add them to one another's groups.
#+BEGIN_EXAMPLE
sudo usermod -aG clamav amavisd
sudo usermod -aG amavisd clamav
#+END_EXAMPLE
Alternatively, edit the config files to run both processes as the same
user.
*** ClamAV
Enable the daemon and the service =freshclam=, whch will keep the virus
definitions updated at regular intervals.
#+BEGIN_EXAMPLE
systemctl enable clamav-daemon
systemctl start clamav-daemon
systemctl enable freshclam
systemctl start freshclam
#+END_EXAMPLE
**** Updating virus definitions
At times it may be necessary to update ClamAV definitions manually. To
do so, simply run =sudo freshclam=. If the update process hangs, it
might be easier to remove the old definitions and redownload the current set.
#+BEGIN_EXAMPLE
# clean the old definitions
sudo rm -rf /var/lib/clamav/daily
# download new
sudo freshclam
# reload daemon
sudo systemctl restart clamav-daemon
#+END_EXAMPLE
*** Amavis
Settings in =/etc/amavisd/amavisd.conf= need to be changed to direct
mail to ClamAV for virus scanning.
 #+BEGIN_EXAMPLE
# virus_mapper_* =[1]
# ..add clamav socket
 #+END_EXAMPLE
Then enable the service.
#+BEGIN_EXAMPLE
systemctl enable amavisd
systemctl start amavisd
#+END_EXAMPLE
* Folders
** etc/
*** postfix/
**** main.cf
#+BEGIN_EXAMPLE
# COMPATIBILITY
compatibility_level = 2

# QUEUE AND PROCESS OWNERSHIP
# mail_owner = postfix

# INTERNET HOST AND DOMAIN NAMES
myhostname = example.com
mydomain = example.com

# SENDING MAIL
myorigin = $myhostname

# RECEIVING MAIL
#proxy_interfaces =
inet_protocols = ipv4 
mydestination =

# REJECTING MAIL FOR UNKNOWN LOCAL USERS
local_recipient_maps = $virtual_mailbox_maps

# TRUST AND RELAY CONTROL
mynetworks = 127.0.0.0/8
relay_domains = $mydestination

# INTERNET OR INTRANET
# relayhost =

# REJECTING UNKNOWN RELAY USERS
relay_recipient_maps = hash:/etc/postfix/relay_recipients


# ALIAS DATABASE
alias_maps = hash:/etc/postfix/aliases
alias_database = $alias_maps

# ADDRESS EXTENSIONS (e.g., user+foo)
# DEBUGGING CONTROL
# debug_peer_level = 2

debugger_command =
	 PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin
	 ddd $daemon_directory/$process_name $process_id & sleep 5

# Virtual mapping
virtual_uid_maps = static:5000
virtual_gid_maps = static:5000
virtual_mailbox_base = /var/mail/vmail
virtual_transport = virtual
virtual_mailbox_domains = pgsql:/etc/postfix/virtual_mailbox_domains.cf
virtual_mailbox_maps = pgsql:/etc/postfix/virtual_mailbox_maps.cf
virtual_alias_maps = pgsql:/etc/postfix/virtual_alias_maps.cf
local_transport = virtual
local_recipient_maps = $virtual_mailbox_maps
transport_maps = hash:/etc/postfix/transport

# Enable SASL and blacklists
disable_vrfy_command = yes
# smtpd_delay_reject = yes
smtpd_helo_required = yes
smtpd_helo_restrictions =
        permit_mynetworks,
        reject_non_fqdn_helo_hostname,
        reject_invalid_helo_hostname,
        permit
smtpd_recipient_restrictions =
        permit_sasl_authenticated,
        reject_unauth_pipelining,
        reject_invalid_hostname,
        reject_non_fqdn_hostname,
        reject_non_fqdn_recipient,
        reject_unknown_recipient_domain,
        reject_unauth_destination,
        permit_mynetworks,
        reject_rbl_client zen.spamhaus.org,
        reject_rbl_client bl.spamcop.net,
        permit

# Use Dovecot for SASL to aunthenticate SMTP
broken_sasl_auth_clients = yes
smtpd_sasl_type = dovecot
smtpd_sasl_path = /var/run/dovecot/auth-client
smtpd_sasl_auth_enable = yes
# smtpd_sasl_security_options = noanonymous
# smtpd_sasl_local_domain =
# smtpd_sasl_authenticated_header = no

# Add SSL with certificate
smtpd_use_tls = yes
smtpd_tls_key_file = /etc/letsencrypt/live/example.com/privkey.pem
smtpd_tls_cert_file = /etc/letsencrypt/live/example.com/fullchain.pem
!!smtpd_tls_dh1024_param_file!!
smtpd_tls_security_level=may
smtpd_tls_auth_only = yes
smtpd_tls_loglevel = 3
smtpd_tls_received_header = yes
smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1
smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1
smtpd_tls_mandatory_ciphers = high
tls_preempt_cipherlist = yes
tls_high_cipherlist = EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA
smtpd_tls_eecdh_grade = ultra

# Add support for OpenDKIM
milter_protocol = 2
milter_default_action = accept
smtpd_milters = unix:/var/run/opendkim/opendkim.sock
non_smtpd_milters = unix:/var/run/opendkim/opendkim.sock
#+END_EXAMPLE
**** master.cf
Option flags passed to protocols will override defaults and settings in main.cf.
#+BEGIN_EXAMPLE
#
# Postfix master process configuration file.  For details on the format
# of the file, see the master(5) manual page (command: "man 5 master" or
# on-line: http://www.postfix.org/master.5.html).
#
# Do not forget to execute "postfix reload" after editing this file.
#
# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (no)    (never) (100)
# ==========================================================================
#smtp      inet  n       -       n       -       -       smtpd
#smtp      inet  n       -       n       -       1       postscreen
#smtpd     pass  -       -       n       -       -       smtpd
#dnsblog   unix  -       -       n       -       0       dnsblog
#tlsproxy  unix  -       -       n       -       0       tlsproxy
smtp       inet n       -       n       -       -       smtpd
  -o content_filter=amavisfeed:[127.0.0.1]:10024
submission inet n       -       n       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_recipient_restrictions=
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING
smtps     inet  n       -       n       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_recipient_restrictions=
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING
#628       inet  n       -       n       -       -       qmqpd
pickup    unix  n       -       n       60      1       pickup
cleanup   unix  n       -       n       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
#qmgr     unix  n       -       n       300     1       oqmgr
tlsmgr    unix  -       -       n       1000?   1       tlsmgr
rewrite   unix  -       -       n       -       -       trivial-rewrite
bounce    unix  -       -       n       -       0       bounce
defer     unix  -       -       n       -       0       bounce
trace     unix  -       -       n       -       0       bounce
verify    unix  -       -       n       -       1       verify
flush     unix  n       -       n       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       n       -       -       smtp
relay     unix  -       -       n       -       -       smtp
#       -o smtp_helo_timeout=5 -o smtp_connect_timeout=5
showq     unix  n       -       n       -       -       showq
error     unix  -       -       n       -       -       error
retry     unix  -       -       n       -       -       error
discard   unix  -       -       n       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       y       -       -       lmtp
anvil     unix  -       -       n       -       1       anvil
scache    unix  -       -       n       -       1       scache
#
# ====================================================================
#
# anti spam & anti virus section
#
amavisfeed      unix  -    -       n       -       2       smtp
 -o smtp_data_done_timeout=1200
 -o smtp_send_xforward_command=yes
 -o disable_dns_lookups=yes
 -o max_use=20
127.0.0.1:10025 inet n  -       y       -       -       smtpd
 -o content_filter=
 -o smtpd_delay_reject=no
 -o smtpd_client_restrictions=permit_mynetworks,reject
 -o smtpd_helo_restrictions=
 -o smtpd_sender_restrictions=
 -o smtpd_recipient_restrictions=permit_mynetworks,reject
 -o smtpd_data_restrictions=reject_unauth_pipelining
 -o smtpd_end_of_data_restrictions=
 -o mynetworks=127.0.0.0/8
 -o smtpd_error_sleep_time=0
 -o smtpd_soft_error_limit=1001 
 -o smtpd_hard_error_limit=1000
 -o smtpd_client_connection_count_limit=0
 -o smtpd_client_connection_rate_limit=0
 -o receive_override_options=no_header_body_checks,no_unknown_recipient_checks,no_milters
 -o local_header_rewrite_clients=
#spamassassin unix -     n       n       -       -       pipe
#  flags=R user=spamd argv=/usr/bin/spamc -f -e /usr/sbin/sendmail -oi -f ${sender} ${recipient}
#policyd-spf  unix  -       n       n       -       0       spawn
#  user=nobody argv=/usr/bin/policyd-spf
dovecot   unix  -       n       n       -       -       pipe
  flags=DRhu user=vmail:vmail argv=/usr/lib/dovecot/deliver -f ${sender} -d ${recipient}
#+END_EXAMPLE
**** virtual _ alias _ maps.cf
#+BEGIN_EXAMPLE
user = postfix
password = DB_PASSWORD
hosts = localhost
dbname = postfix
table = alias
select_field = goto
where_field = address
#+END_EXAMPLE
**** virtual _ mailbox _ domains.cf
#+BEGIN_EXAMPLE
user = postfix
password = DB_PASSWORD
hosts = localhost
dbname = postfix
table = domain
select_field = domain
where_field = domain
#+END_EXAMPLE
**** virtual _ mailbox _ maps.cf
#+BEGIN_EXAMPLE
user = postfix
password = DB_PASSWORD
hosts = localhost
dbname = postfix
table = mailbox
select_field = maildir
where_field = username
#+END_EXAMPLE
*** dovecot/
**** conf.d/
***** 10-auth.conf
#+BEGIN_EXAMPLE
auth_mechanisms = plain login
disable_plaintext_auth = yes

!include auth-sql.conf.ext
#+END_EXAMPLE
***** 10-mail.conf
#+BEGIN_EXAMPLE
mail_location = maildir:/var/mail/vmail/%d/%n
mail_privileged_group = mail
mail_uid = vmail
mail_gid = vmail
first_valid_uid = 5000
last_valid_uid = 5000

namespace inbox {
    type = private
    separator = /
    prefix =
    inbox = yes
    hidden = no
    
    mailbox Trash {
        auto = no
        special_use = \Trash
    }

    mailbox Drafts {
        auto = no
        special_use = \Drafts
    }

    mailbox Sent {
        auto = subscribe                 
        special_use = \Sent
    }

    mailbox "Sent Messages" {
        auto = no
        special_use = \Sent
    }

    mailbox Spam {
        auto = create
        special_use = \Junk
    }

}
#+END_EXAMPLE
***** 10-master.conf
#+BEGIN_EXAMPLE
service imap-login {
    inet_listener imap {
        port = 0
    }
    inet_listener imaps {
        port = 993
        ssl = yes
    }
}
service pop3-login {
    inet_listener pop3 {
        port = 0
    }
    inet_listener pop3s {
        # port = 995
        # ssl = yes
        port = 0
    }
}
service auth {
    unix_listener auth-client {
        mode = 0660
        user = postfix
        group = postfix
    }
    user = root
}
#+END_EXAMPLE
***** 10-ssl.conf
#+BEGIN_EXAMPLE
ssl = required
ssl_cert = </etc/letsencrypt/live/example.com/fullchain.pem
ssl_key = </etc/letsencrypt/live/example.com/privkey.pem
ssl_dh = </etc/dovecot/dh.pem

# SSL protocols to use
# ssl_protocols = !SSLv3

# SSL ciphers to use
ssl_cipher_list = ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS


#+END_EXAMPLE
***** auth-sql.conf.ext
#+BEGIN_EXAMPLE
passdb {
    driver = sql
    args = /etc/dovecot/dovecot-sql.conf
}
userdb {
    driver = sql
    args = /etc/dovecot/dovecot-sql.conf
}
#+END_EXAMPLE
**** dovecot.conf
#+BEGIN_EXAMPLE
postmaster_address = postmaster@example.com
protocols = imap

!include conf.d/*.conf
!include_try local.conf
#+END_EXAMPLE
**** dovecot-sql.conf
#+BEGIN_EXAMPLE
driver = pgsql
connect = host=/var/run/postgresql dbname=postfix user=postfix password=DBPASSWORD

default_pass_scheme = BLF-CRYPT

user_query = SELECT '/var/mail/vmail/%d/%n' AS home, 'maildir:/var/mail/vmail/%d/%n' AS mail, 5000 AS uid, 5000 AS gid FROM mailbox WHERE username = '%u' AND active = '1'

password_query = SELECT username as user, password, '/var/mail/vmail/%d/%n' as userdb_home, 'maildir:/var/mail/vmail/%d/%n' as userdb_mail, 5000 as userdb_uid, 5000 as userdb_gid FROM mailbox WHERE username = '%u' AND active = '1'
#+END_EXAMPLE
*** webapps/
**** postfixadmin/
***** config.inc.php
***** config.local.php
#+BEGIN_EXAMPLE
$CONF['configured'] =        true;
$CONF['setup_password'] =    '';

// Database config
$CONF['database_type'] =     'pgsql';
$CONF['database_host'] =     'localhost';
$CONF['database_user'] =     'postfix';
$CONF['database_password'] = 'PASSWORD';
$CONF['database_name'] =     'postfix';

// Site admin
$CONF['admin_email'] = 'admin@example.com';
// Site admin name
// This will be used as signature in notification messages
$CONF['admin_name'] = 'admin';

// Passwords and encryption
$CONF['encrypt'] = 'dovecot:BLF-CRYPT';
$CONF['password_validation'] = array(
# '/reg exp/'         => '$PALANG key (optional: + parameter)',
  '/.{5}/'            => 'password_too_short 5',  # minimum length 5 characters
  '/([a-zA-Z].*){3}/' => 'password_no_characters 3'  # must contain at least 3 letters
# '/([0-9].*){2}/'    => 'password_no_digits 2', # must contain at least 2 digits
    );
$CONF['dovecotpw'] = "/usr/sbin/doveadm pw -r 12";

// Default aliases to create
$CONF['default_aliases'] = array (
  'admin'      => 'admin@example.com',
  'postmaster' => 'postmaster@example.com'
);

// Location of administrative scripts
$CONF['mailbox_postcreation_script'] = 'sudo -u vmail /usr/local/bin/postfixadmin-mailbox-postcreation.sh';
$CONF['mailbox_postdeletion_script'] = 'sudo -u vmail /usr/local/bin/postfixadmin-mailbox-postdeletion.sh';
$CONF['domain_postdeletion_script'] = 'sudo -u vmail /usr/local/bin/postfixadmin-domain-postdeletion.sh';

$['vacation_domain'] = 'autoreply.example.com';

// Below information will be on all pages.
// If you don't want the footer information to appear set this to 'NO'.
$CONF['show_footer_text'] = 'YES';
$CONF['footer_text'] = 'Return to example.com';
$CONF['footer_link = 'https://example.com';
#+END_EXAMPLE
*** opendkim/
**** opendkim.conf
#+BEGIN_EXAMPLE
Domain           example.com
KeyFile          /etc/opendkim/keys/example.com/dkim.key
OverSignHeaders  From
PidFile          /var/run/opendkim/opendkim.pid
RequireSafeKeys  No
Selector         Mail
Socket           unix:/var/run/opendkim/opendkim.sock
Syslog           Yes
UMask            007
#+END_EXAMPLE
** var/
*** mail/ -> spool/mail
**** vmail (drwxrws--- vmail:vmail)
***** domain.com (drwx--S--- vmail:vmail
** usr/
*** share/
**** doc/
***** postfixadmin/
****** ADDITIONS/
******* postfixadmin - * - *.sh
Symlink to /usr/local/bin and make executable; referred to in /etc/webapps/postfixadmin/config.local.php
***** dovecot/
****** example-config/
